USE todo;

CREATE TABLE IF NOT EXISTS task (
    id INT AUTO_INCREMENT PRIMARY KEY,
    taskname VARCHAR(255) NOT NULL,
    taskstatus VARCHAR(255) NOT NULL,
    taskcategory VARCHAR(255) NOT NULL
);
